Repository jenkins-x/jx-kube-client, pull requests merged in 2020-06, with the labels that each got.

#1 chore: fix change log generation
  changelog.sh
  jenkins-x.yml
Labels: size/S

#2 chore: bump go to 1.13
  go.mod
Labels: size/XS

#3 feat: allow kubeconfig location to be configured
  Makefile
  README.md
  pkg/kubeclient/interface.go
  pkg/kubeclient/kube.go
Labels: lgtm, size/M

#4 chore: add OWNERS file
  OWNERS
Labels: lgtm, size/S

#5 feat: add linter and fix lint issues
  Makefile
  hack/install_golint.sh
  hack/linter.sh
  jenkins-x.yml
  pkg/kubeclient/kube.go
Labels: approved, lgtm, size/L

#6 chore: add go report card
  README.md
Labels: approved, lgtm, size/XS

#8 chore: moved linter config into config file
  .golangci.yml
  hack/linter.sh
  pkg/kubeclient/kube.go
  pkg/kubeclient/kube_test.go
Labels: approved, lgtm, size/L
